-- ============================================================================
-- SEC-005: Webhook Events table for idempotent processing
-- Prevents duplicate processing of Stripe webhook events on retries.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.webhook_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id TEXT NOT NULL UNIQUE,
    event_type TEXT NOT NULL DEFAULT '',
    processed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for fast lookups by event_id
CREATE INDEX IF NOT EXISTS idx_webhook_events_event_id ON public.webhook_events (event_id);

-- RLS: Only service_role should access this table
ALTER TABLE public.webhook_events ENABLE ROW LEVEL SECURITY;

-- Allow service_role full access (used by webhook handler)
CREATE POLICY "Service role full access on webhook_events"
    ON public.webhook_events
    FOR ALL
    USING (auth.role() = 'service_role')
    WITH CHECK (auth.role() = 'service_role');

-- Auto-cleanup: Remove events older than 30 days (optional, run via cron)
-- DELETE FROM public.webhook_events WHERE processed_at < NOW() - INTERVAL '30 days';
